# Setup
title:               PDI
tagline:             'OpenCV em Python'
description:         'Um blog destinado a compartilhar algumas experiências no mundo da programação. Feito com <a href="https://jekyllrb.com" target="_blank">Jekyll</a> e <a href="https://lanyon.getpoole.com/" target="_blank">Lanyon</a>.'
url:                 https://lucasamds.github.io
baseurl:             '/PDI/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Lucas Silva
  url:               https://twitter.com/lucsams
  email:             lucsamds@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
